apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiali-pvc
  namespace: istio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
--- 

apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio
spec:
  deployment:
    accessible_namespaces: ["**"]
    volumes:
      - name: kiali-storage
        persistentVolumeClaim:
          claimName: kiali-pvc
    volumeMounts:
      - mountPath: /data
        name: kiali-storage
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/e2e-az-name
                  operator: In
                  values:
                    - e2e-az1
                    - e2e-az2
  external_services:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    grafana:
      enabled: true
      in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
      url: "http://34.46.3.160"
      auth:
        type: "basic"
        username: "admin"
        password: "prom-operator"
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            namespace: "var-namespace"
            workload: "var-workload"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
        
