apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio
spec:
  deployment:
    accessible_namespaces: ["**"]
  external_services:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    grafana:
      enabled: true
      in_cluster_url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
      url: "http://34.46.3.160"
      auth:
        type: "basic"
        username: "admin"
        password: "prom-operator"      
      dashboards:
        - name: "Istio Service Dashboard"
          variables:
            namespace: "var-namespace"
            service: "var-service"
        - name: "Istio Workload Dashboard"
          variables:
            namespace: "var-namespace"
            workload: "var-workload"
        - name: "Istio Mesh Dashboard"
        - name: "Istio Control Plane Dashboard"
        - name: "Istio Performance Dashboard"
        - name: "Istio Wasm Extension Dashboard"
