{
 "title": "Monitoramento",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods não rodando",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\"}",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  { "title": "Uso de Recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Estados dos Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\"}",
     "legendFormat": "{{pod}} - Reinícios"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (pod, namespace)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (pod, namespace)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  }
 ]
}