

# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html

# apiVersion: elasticsearch.k8s.elastic.co/v1
# kind: Elasticsearch
# metadata:
#   name: quickstart
#   namespace: efk
# spec:
#   version: 8.15.0
#   nodeSets:
#   - name: default
#     count: 1
#     config:
#       node.store.allow_mmap: false
#     volumeClaimTemplates:
#     - metadata:
#         name: elasticsearch-data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 25Gi
#         storageClassName: gp3


apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: efk
spec:
  version: 8.15.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
        storageClassName: gp3
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: monitoring
                  operator: In
                  values:
                  - "true"
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "4Gi"
