apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: efs-sc #gp3
  accessModes:
    - ReadWriteMany #ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
