apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-045df97becf34c025 # Substitua por seu ID EFS
  directoryPerms: "700"
  # gidRangeStart: "1000"
  # gidRangeEnd: "2000"
  # uid: "1000"
  # gid: "1000"
reclaimPolicy: Retain
volumeBindingMode: Immediate


