apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadog-logs-pvc
  #namespace: <namespace> # Defina o namespace correto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Defina o tamanho do volume conforme necessário
  storageClassName: gp3 # Utilize a StorageClass disponível no seu cluster
